package docs

import (
"encoding/json"
"fmt"
"os"
"path/filepath"
"time"
)

type DocManifest struct {
Platform   string    `json:"platform"`
GeneratedAt time.Time `json:"generated_at"`
Docs       []DocInfo  `json:"docs"`
}

type DocInfo struct {
Name     string `json:"name"`
Path     string `json:"path"`
Status   string `json:"status"` // exists, missing, stale
Required bool   `json:"required"`
}

type Generator struct {
muahDir string
rootDir string
platform string
}

func NewGenerator(muahDir, rootDir string) *Generator {
return &Generator{
muahDir:  muahDir,
rootDir:  rootDir,
platform: DetectPlatform(rootDir),
}
}

func (g *Generator) Generate() (*DocManifest, error) {
manifest := &DocManifest{
Platform:    g.platform,
GeneratedAt: time.Now(),
}

switch g.platform {
case "github":
manifest.Docs = g.githubDocs()
case "gitlab":
manifest.Docs = g.gitlabDocs()
default:
manifest.Docs = g.genericDocs()
}

for i, doc := range manifest.Docs {
fullPath := filepath.Join(g.rootDir, doc.Path)
if _, err := os.Stat(fullPath); err == nil {
manifest.Docs[i].Status = "exists"
} else {
manifest.Docs[i].Status = "missing"
}
}

if err := g.saveManifest(manifest); err != nil {
return nil, err
}
return manifest, nil
}

func (g *Generator) githubDocs() []DocInfo {
return []DocInfo{
{Name: "README", Path: "README.md", Required: true},
{Name: "LICENSE", Path: "LICENSE", Required: true},
{Name: "CONTRIBUTING", Path: "CONTRIBUTING.md", Required: false},
{Name: "CODE_OF_CONDUCT", Path: "CODE_OF_CONDUCT.md", Required: false},
{Name: "SECURITY", Path: "SECURITY.md", Required: true},
{Name: "CHANGELOG", Path: "CHANGELOG.md", Required: false},
{Name: "PR Template", Path: ".github/PULL_REQUEST_TEMPLATE.md", Required: false},
{Name: "Bug Report", Path: ".github/ISSUE_TEMPLATE/bug_report.md", Required: false},
{Name: "Feature Request", Path: ".github/ISSUE_TEMPLATE/feature_request.md", Required: false},
{Name: "CODEOWNERS", Path: ".github/CODEOWNERS", Required: false},
{Name: "Dependabot", Path: ".github/dependabot.yml", Required: false},
}
}

func (g *Generator) gitlabDocs() []DocInfo {
return []DocInfo{
{Name: "README", Path: "README.md", Required: true},
{Name: "LICENSE", Path: "LICENSE", Required: true},
{Name: "CONTRIBUTING", Path: "CONTRIBUTING.md", Required: false},
{Name: "CHANGELOG", Path: "CHANGELOG.md", Required: false},
}
}

func (g *Generator) genericDocs() []DocInfo {
return []DocInfo{
{Name: "README", Path: "README.md", Required: true},
{Name: "LICENSE", Path: "LICENSE", Required: true},
{Name: "CHANGELOG", Path: "CHANGELOG.md", Required: false},
{Name: "ARCHITECTURE", Path: "ARCHITECTURE.md", Required: false},
}
}

func (g *Generator) saveManifest(manifest *DocManifest) error {
path := filepath.Join(g.muahDir, "docs", "doc-manifest.json")
os.MkdirAll(filepath.Dir(path), 0755)
data, err := json.MarshalIndent(manifest, "", "  ")
if err != nil {
return err
}
return os.WriteFile(path, data, 0644)
}

// CreateMissingDocs generates stub content for missing required docs
func (g *Generator) CreateMissingDocs(manifest *DocManifest) error {
for _, doc := range manifest.Docs {
if doc.Status != "missing" || !doc.Required {
continue
}
content := g.defaultContent(doc.Name)
fullPath := filepath.Join(g.rootDir, doc.Path)
os.MkdirAll(filepath.Dir(fullPath), 0755)
// Only create if does not already exist
if _, err := os.Stat(fullPath); os.IsNotExist(err) {
if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
return fmt.Errorf("create %s: %w", doc.Path, err)
}
}
}
return nil
}

func (g *Generator) defaultContent(name string) string {
switch name {
case "README":
return "# Project\n\nAuto-generated by muah-runner.\n"
case "LICENSE":
return "MIT License\n\nCopyright (c) " + fmt.Sprintf("%d", time.Now().Year()) + "\n"
case "SECURITY":
return "# Security Policy\n\nPlease report vulnerabilities to the maintainers privately.\n"
case "CONTRIBUTING":
return "# Contributing\n\nThank you for contributing!\n"
default:
return fmt.Sprintf("# %s\n\nAuto-generated by muah-runner.\n", name)
}
}
