#!/usr/bin/env bash
# scripts/install-playwright.sh — Install Playwright + Chromium for muah-runner.
# Platform-agnostic: Linux, macOS, Windows (Git Bash / WSL).
#
# Usage:
#   bash scripts/install-playwright.sh
#   # or via muah-runner:
#   muah-runner playwright setup

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${BLUE}[playwright]${NC} $*"; }
success() { echo -e "${GREEN}[playwright]${NC} ✓ $*"; }
warn()    { echo -e "${YELLOW}[playwright]${NC} ⚠ $*"; }
die()     { echo -e "${RED}[playwright]${NC} ✗ $*" >&2; exit 1; }

# ── Check Node.js ─────────────────────────────────────────────────────────────
check_node() {
  if ! command -v node &>/dev/null; then
    die "Node.js is required. Install it from https://nodejs.org (LTS recommended)"
  fi
  NODE_VER="$(node --version)"
  info "Node.js: ${NODE_VER}"

  # Need Node ≥ 16
  NODE_MAJOR="$(echo "$NODE_VER" | sed 's/v//' | cut -d. -f1)"
  if [ "$NODE_MAJOR" -lt 16 ]; then
    die "Node.js ≥ 16 required, found ${NODE_VER}"
  fi

  if ! command -v npx &>/dev/null; then
    die "npx not found. Upgrade npm: npm install -g npm"
  fi
}

# ── Install @playwright/test ──────────────────────────────────────────────────
install_playwright_package() {
  info "Installing @playwright/test..."
  if [ -f "package.json" ]; then
    # Project already has package.json — install as dev dependency
    npm install --save-dev @playwright/test 2>/dev/null \
      || npx playwright install 2>/dev/null \
      || warn "npm install failed — trying global install"
  fi
  # Always ensure npx playwright is available
  if ! npx playwright --version &>/dev/null 2>&1; then
    npm install -g @playwright/test || die "Failed to install @playwright/test globally"
  fi
  PW_VERSION="$(npx playwright --version 2>/dev/null || echo 'unknown')"
  success "Playwright ${PW_VERSION} installed"
}

# ── Install Chromium browser ──────────────────────────────────────────────────
install_chromium() {
  info "Installing Chromium browser..."
  npx playwright install chromium || die "Failed to install Chromium"
  success "Chromium installed"
}

# ── Install system dependencies (Linux only) ──────────────────────────────────
install_system_deps() {
  if [ "$(uname -s)" != "Linux" ]; then
    return
  fi
  info "Installing system dependencies for Playwright on Linux..."
  if command -v apt-get &>/dev/null; then
    sudo apt-get update -qq
    npx playwright install-deps chromium 2>/dev/null \
      || sudo apt-get install -y --no-install-recommends \
           libnss3 libnspr4 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 \
           libcups2 libdrm2 libxcomposite1 libxdamage1 libxrandr2 \
           libgbm1 libxkbcommon0 libasound2 2>/dev/null || true
    success "System dependencies installed"
  elif command -v yum &>/dev/null; then
    npx playwright install-deps chromium 2>/dev/null || true
  else
    warn "Unknown package manager — skipping system deps. Run 'npx playwright install-deps' manually if needed."
  fi
}

# ── Write playwright.config.js if not present ────────────────────────────────
write_config() {
  local config_file="playwright.config.js"
  if [ -f "$config_file" ]; then
    info "playwright.config.js already exists — skipping"
    return
  fi
  info "Writing default playwright.config.js..."
  cat > "$config_file" << 'PWEOF'
// playwright.config.js — Generated by muah-runner
const { defineConfig, devices } = require('@playwright/test');

module.exports = defineConfig({
  testDir: './tests/playwright',
  timeout: 30000,
  retries: 1,
  use: {
    headless: true,
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
  outputDir: '.muah/playwright/results',
});
PWEOF
  success "playwright.config.js written"
}

# ── Update .muah/ state ───────────────────────────────────────────────────────
update_muah() {
  local muah_dir="${MUAH_DIR:-.muah}"
  if [ ! -d "$muah_dir" ]; then
    return
  fi
  local pw_config="${muah_dir}/mcp/native/playwright-mcp.json"
  mkdir -p "$(dirname "$pw_config")"
  cat > "$pw_config" << MCPEOF
{
  "name": "playwright-mcp",
  "type": "native",
  "status": "installed",
  "version": "$(npx playwright --version 2>/dev/null || echo 'unknown')",
  "browsers": ["chromium"],
  "installed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
MCPEOF
  success ".muah/mcp/native/playwright-mcp.json updated"
}

# ── Verify ────────────────────────────────────────────────────────────────────
verify() {
  info "Verifying Playwright installation..."
  npx playwright --version &>/dev/null && success "Playwright is ready" \
    || warn "Playwright installed but 'npx playwright' not found in PATH"
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  echo ""
  echo "  🎭 Playwright setup for muah-runner"
  echo "  ─────────────────────────────────────"
  echo ""
  check_node
  install_playwright_package
  install_chromium
  install_system_deps
  write_config
  update_muah
  verify
  echo ""
  success "Playwright setup complete!"
  echo ""
  echo "  Usage:"
  echo "    muah-runner playwright test                   # Run test suite"
  echo "    muah-runner playwright screenshot <url>       # Take a screenshot"
  echo "    muah-runner playwright audit <url>            # Accessibility audit"
  echo ""
}

main "$@"
